spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
        security: TRACE
#          oauth2:
#            client:
#              web:
#                OAuth2AuthorizationRequestRedirectFilter: TRACE
#                OAuth2LoginAuthenticationFilter: TRACE
#                OAuth2AuthorizationCodeGrantFilter: TRACE
#                OAuth2AccessTokenResponseClient: TRACE
    com:
      example:
        googleoidcapp:
          repository: TRACE
